### PR TITLE
PHP Parse error:  syntax error, unexpected ''

### PR DESCRIPTION
**Pull request by ssmarco**
I was trying to learn more about this module and encountered an error hence this fix.

### CODE REVIEW

**Comment by HARVS1789UK** [comment]
Can see no reason why this tiny fix wouldn't be accepted, suspect the maintainers just haven't had sight of it @sheadawson @JorisDebonnet @ajshort Could a maintainer be assigned to this?

**Comment by sheadawson** [comment]
I don't have write permissions, sorry! @mattclegg ?

**Comment by mattclegg** [comment]
Yeah sorry, this shouldn't have been committed to master. Can the Travis tests be enabled on this repo to catch errors like this?

**Comment by gordonbanderson** [comment]
@mattclegg The travis file, https://github.com/symbiote/silverstripe-memberprofiles/blob/master/.travis.yml, has PHP_CS setup.  That ought to have picked up the error

**Comment by mattclegg** [comment]
Yes you're right @gordonbanderson, but Travis currently isn't active for the repository; https://travis-ci.org/github/symbiote/silverstripe-memberprofiles

**Comment by nglasl** [comment]
Appreciate all the input from everyone here, and the pull requests submitted to fix the issues. I've now merged https://github.com/symbiote/silverstripe-memberprofiles/pull/172 (big thanks @mattclegg), and I've made sure it's now enabled over on https://travis-ci.org/github/symbiote/silverstripe-memberprofiles. This specific problem has been resolved as part of those changes, as can be seen from the successful builds :smile:

**Pull request closed without merging**
