### PR TITLE
Add SS5 as supported version

### PR DESCRIPTION
**Pull request by Firesphere**

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
FYI #183 is needed for SS5 support too not just updating the composer file :) there's some deprecated api's that need to be replaced.

**Comment by Firesphere** [comment]
> 

I'm aware :) I simply "started" the PR. There's more than only the API change to it :)

**Comment by UndefinedOffset** [comment]
@GuySartorelli any chance someone from the Symbiote team can have a look at this and #183

**Comment by nyeholt** [comment]
Handled in #190

**Pull request closed without merging**
